### ISSUE TITLE
Problem with site

### ISSUE THREAD

**Issue by joshuaTsmith** [TaylanTatli/Halve#2]
I'm new to github and coding so please forgive me if I am just missing something obvious.

I 'forked' Halve and then changed the name to joshuaTsmith.github.io (for my github page), however, if you go to that page you will see my site has obvious formatting issues. 

It looks nothing like what you have displayed. What do I need to do to fix this?

**Comment by joshuaTsmith** [comment]
Ah, I see... It was due to my browser. Chrome was saying that there were unsafe elements on the site. (currently investigating what in particular it is pointing to)

**Comment by TaylanTatli** [comment]
Did you set your `url` in your `_config.yml`? Did you remove your repo? I can't see it on your profile.

**Comment by joshuaTsmith** [comment]
And it works now! Thank you.
