### ISSUE TITLE
Can we add support for https? (Adding ssl layer)

### ISSUE THREAD

**Issue by quzhi1** [TaylanTatli/Halve#27]
I saw your website (http://vangeltzo.com/) is using this template. When I change the url to https://vangeltzo.com/, the website layout will be messed up. Can you add https support for this template?

**Comment by TaylanTatli** [comment]
Change your `url: http://quzhi1.github.io/` line to `url: https://quzhi1.github.io/`.

**Comment by quzhi1** [comment]
I tried to change the url to https in _config.yml, and I ran it locally (https://127.0.0.1:4000/). However, I got the following in the console:

"ERROR bad Request-Line `\x16\x03\x01\x00?\x01\x00\x00?\x03\x03K}z????\x16?f*?\x02\x03?D#5z=??V??/?m?QF\x00\x00\x1E?+?/̨̩?,?0?'."

Is there any other file I need to change?

**Comment by tanto259** [comment]
Try building your site online on [GitHub Pages](https://pages.github.com) or [Netlify](https://www.netlify.com). 

Building it on `localhost` or `127.0.0.1` won't work since it doesn't have a SSL certificate.

**Comment by quzhi1** [comment]
It works! Thanks @tanto259 and @TaylanTatli !
