### ISSUE TITLE
questions related to using your jekyll theme for my portfolio

### ISSUE THREAD

**Issue by siliwang** [TaylanTatli/Halve#43]
Hi Taylan,

Thank you very much for building such a beautiful template.  I absolutely love it.  I am creating my analytics portfolio with your template and have two questions:

1. When I navigate from my homepage to "posts", the http://...  (domain name?) is still yours.  The reader can be confused about that.  How could I change it to be consistent?

2. There is a logo on the post list page and links to the original unchanged homepage.  How could I delete it or link to my own homepage?

Thanks a lot and I greatly appreciate your help in advance!

Sincerely,
Sili

**Comment by libeclipse** [comment]
Modify your config.yml

**Comment by siliwang** [comment]
It worked! Thanks so much!!
