### ISSUE TITLE
how to add projects in the project page?

### ISSUE THREAD

**Issue by siliwang** [TaylanTatli/Halve#44]
Any suggestion on adding projects in the project page?

Greatly appreciated.

**Comment by libeclipse** [comment]
It's in the projects folder.

**Comment by siliwang** [comment]
I guess you mean the _data folder (since there is no projects folder)?  I tried to add in the projects.yaml
file but no change happened.

**Comment by libeclipse** [comment]
Yep, that's it. You probably added it wrong and it failed to build. Check
this repo for an example. Did github email you a build log?

**Comment by siliwang** [comment]
Thanks. Which repo you are talking about ?  I simply copied and pasted the original code, in an attempt only to increase the numbers. Did not receive any build log.  

Also a side question: I replace favicon.png and favicon.ico with my choice. Yet no change happening.

**Comment by libeclipse** [comment]
Are you using a CDN or something that's caching the site? Or is your
browser caching it?

**Comment by siliwang** [comment]
worked after clearing caches.  Thanks a lot!  both problems are solved.
