### ISSUE TITLE
How can I change font for words? 

### ISSUE THREAD

**Issue by siliwang** [TaylanTatli/Halve#48]
Hi! I would like to change the font for words, especially words in posts.  Is there a way to only change font for posts?  Fine too if you could direct me to the place to change font for all.

Thanks and again it is a beautiful theme.

**Comment by siliwang** [comment]
I think the current font is beautiful but still interested in knowing how to change font size/type of title and body.  Hope to experiment around a little.  Greatly appreciate your help in advance!

**Comment by tanto259** [comment]
Fonts file are located at the `/assets/fonts` [directory](https://github.com/TaylanTatli/Halve/tree/afa65c0b2d05e4e33dbc5d3fe2d3c2ef231f466b/assets/fonts), with links to the `/assets/_sass/vendor/fonts.scss` [file](https://github.com/TaylanTatli/Halve/blob/afa65c0b2d05e4e33dbc5d3fe2d3c2ef231f466b/assets/_sass/vendor/fonts.scss) and defined for use at the site at the `/assets/_sass/_variable.scss` [file](https://github.com/TaylanTatli/Halve/blob/afa65c0b2d05e4e33dbc5d3fe2d3c2ef231f466b/assets/_sass/_variables.scss#L12-L13).

To change font size and margins, etc., edit the `/assets/_sass/_base.scss` and the `/assets/_sass/_site.scss` files.

**Comment by siliwang** [comment]
Awesome! Thank you very much!
