### ISSUE TITLE
How to edit About page

### ISSUE THREAD

**Issue by Ankit4922** [TaylanTatli/Halve#5]
I am not able to edit about page which is the right part of homepage. Can you please tell me of a way to edit it.

**Comment by TaylanTatli** [comment]
https://github.com/Ankit4922/Halve/blob/master/index.md

**Comment by Ankit4922** [comment]
Oh I thought it would be about theme but its about page, Thanks by the way.
One more issue if I'm not troubling you, I changed the favicon.ico and the logo but its not showing.

**Comment by Ankit4922** [comment]
I solved it myself again sorry for troubling you.
